/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import java.awt.Image;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author agund
 */
public class VRegistro extends javax.swing.JDialog {

    /**
     * Creates new form VRegistro
     */
    public VRegistro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         ImageIcon wallpaper=new ImageIcon("src/imagenes/7f31549a-df8d-4058-8fca-22d85e564447.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel5.getWidth(),jLabel5.getHeight(), Image.SCALE_DEFAULT));
        jLabel5.setIcon(icono);
        this.repaint();
        this.setBounds(0,0,icono.getIconWidth(),icono.getIconHeight()+30);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jpwPassword = new javax.swing.JPasswordField();
        jpwRepeatPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jtfUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        jLabel3.setText("Repetir contraseña");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));
        getContentPane().add(jtfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 156, -1));
        getContentPane().add(jpwPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 156, -1));

        jpwRepeatPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpwRepeatPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jpwRepeatPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 156, -1));

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));
        getContentPane().add(jtfUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, -1));

        jLabel4.setText("Nombre Completo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 110, 10));

        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 160, -1));

        jLabel6.setText(" Usuario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 60, 10));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**/
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nusuario=jtfUsuario.getText();
        String nombre = jTextNombre.getText();
        String email = jtfEmail.getText();
        email = email.replaceAll(" ", "");
        String password = String.valueOf(jpwPassword.getPassword());
        String repeatPassword = String.valueOf(jpwRepeatPassword.getPassword());
        String comprobarNombreValido = nombre.replaceAll(" ", "");
        String comprobarCorreo = "";
        if(!email.isEmpty()){
            comprobarCorreo = email.substring(0,1);
        }
        if(nusuario.isEmpty() || nombre.isEmpty() ||email.isEmpty() || password.isEmpty() || repeatPassword.isEmpty() ){
            JOptionPane.showMessageDialog(this, "Campos vacios");
        }else if (!(email.contains("@hotmail.com") || email.contains("@gmail.com") || email.contains("@outlook.com")) || comprobarCorreo.equals("@")){
            JOptionPane.showMessageDialog(this, "Correo invalido");
        }else if(nombre.length() > 40){
            JOptionPane.showMessageDialog(this, "Máximo 40 carácteres en el campo Nombre", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(password.length() < 8 || password.contains(" ")){
            JOptionPane.showMessageDialog(this, "La contraseña debe ser de minimo 8 caractéres y no debe incluir espacios en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(nusuario.contains(" ")){
            JOptionPane.showMessageDialog(this, "El UserName no debe contener espacios en blanco", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(comprobarNombreValido.isEmpty()){
            JOptionPane.showMessageDialog(this, "Complete el campo de Nombre", "Error", JOptionPane.ERROR_MESSAGE);
        }else if(!password.equals(repeatPassword)) {
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        }else {
            Usuario usuario = new Usuario();
            usuario.setNusuario(nusuario);
            usuario.setNombre(nombre);
            usuario.setEmail(email);
            usuario.setPassword(password);
            
            try {
                int result = usuario.create();
                if(result == 1) {
                    JOptionPane.showMessageDialog(this, "Datos almacenados correctamente");
                    this.dispose();
                } else{
                    JOptionPane.showMessageDialog(this, "Ocurrió un error", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (ClassNotFoundException | SQLException | NoSuchAlgorithmException ex) {
                Logger.getLogger(VRegistro.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jpwRepeatPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpwRepeatPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpwRepeatPasswordActionPerformed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VRegistro dialog = new VRegistro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JPasswordField jpwPassword;
    private javax.swing.JPasswordField jpwRepeatPassword;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
